server:
  port: 0
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MONGODB_URL}
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}

  application:
    name: member-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
jwt:
  expiration: ${JWT_EXPIRATION}
  secretKey: ${JWT_SECRETKEY}
  expirationRt: ${JWT_RT_EXPIRATION}
  secretKeyRt: ${JWT_RT_SECRETKEY}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  application:
    name: switht
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
  mvc: # pathmatch 빠지니까 스웨거 null pointer 오류 남
    pathmatch:
      matching-strategy: ant_path_matcher