server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:8081'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS
      routes:
        - id: swithtchat-service
          #         predicates =  product-service로 요청이 들어오면
          predicates:
            - Path=/swithtchat-service/**
          #         filter = 앞 1개 (/product-service) 를 제거하고 product-service로 요청을 보낸다
          filters:
            - StripPrefix=1
          #          아래 uri는 eureka에 등록된 서비스명, 각 서비스마다 spring.application.name으로 등록되어있음
          uri: lb://swithtchat-service

        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
            - StripPrefix=1
          uri: lb://member-service

        - id: speech-service
          predicates:
            - Path=/speech-service/**
          filters:
            - StripPrefix=1
          uri: lb://speech-service

        - id: lesson-service
          predicates:
            - Path=/lesson-service/**
          filters:
            - StripPrefix=1
          uri: lb://lesson-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/