apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: tweety
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "3G"
    nginx.ingress.kubernetes.io/client-body-buffer-size: "3G"
    nginx.ingress.kubernetes.io/affinity: "cookie"  # 세션 스티키니스 활성화
    nginx.ingress.kubernetes.io/session-cookie-name: "teenkiri-session"  # 세션 쿠키 이름
    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"  # 쿠키 해시 알고리즘
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: member