spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/switht_payment
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    tomcat:
      max-active: 5
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
    open-in-view: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}

jwt:
  expiration: 300
  secretKey: ${JWT_SECRET}
  expirationRt: 14400
  secretKeyRt: ${JWT_SECRET_RT}

imp:
  code: ${IMP_CODE}
  key: ${IMP_KEY}
  secret: ${IMP_SECRET}

