apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture-deployment
  namespace: tweety
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecture
  template:
    metadata:
      labels:
        app: lecture
    spec:
      containers:
        - name: lecture
          # AWS의 ecr 주소 사용
          image: 533267389389.dkr.ecr.ap-northeast-2.amazonaws.com/tweety-lecture:latest
          ports:
            - containerPort: 8080
          resources:
            # 최대 할당 가능량
            limits:
              cpu: "1"
              memory: "1000Mi"
            # 최소 할당량
            requests:
              cpu: "0.5"
              memory: "500Mi"
          env:
            - name: JAVA_OPTS
              value: "-Xmx2048m"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: tweety-secrets
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: tweety-secrets
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: tweety-secrets
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: tweety-secrets
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET
                  name: tweety-secrets
            - name: JWT_SECRET_RT
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_RT
                  name: tweety-secrets
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY
                  name: tweety-secrets
            - name: AWS_SECRET
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET
                  name: tweety-secrets
            - name: OPENSEARCH_URL
              valueFrom:
                secretKeyRef:
                  key: OPENSEARCH_URL
                  name: tweety-secrets
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: OPENSEARCH_USERNAME
                  name: tweety-secrets
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: OPENSEARCH_PASSWORD
                  name: tweety-secrets
            - name: KAFKA_SERVER
              valueFrom:
                secretKeyRef:
                  key: KAFKA_SERVER
                  name: tweety-secrets
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name